# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TfgaXhi78IQFhypcQwqQV-j__jIkUh1Z

Introducción
"""

print('hola')

nombre = 'kevin'

print(nombre)

"""Variables"""

numero1=5
numero2=9.25
ciudad="Monterrey"
edad="25"
pago=True



suma=numero1+numero2
print(suma)

print('Estoy en ' + ciudad)

print(ciudad*numero1)

print(pago)

del pag

numero1="pollo"

print("Hombre","Mujer", 5+numero1)

print("mi hijo tiene" + str(numero1) +" anos")

print(int(edad)+numero1)