# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQiXJFf0UhSLMdoqzDExTIsS2ypn-Vus
"""

nombre='Kevin'
print("Hola mi nombres es " +nombre)

edad=20
print("tengo", edad, "años")

lista = ["Agustin","Pedro", "Francisco"]
print(lista[0])
print(lista[2])

n1=5
n2=6
print("Suma: ", n1+n2, "Resta: ", n1-n2, "Multiplicación: ", n1*n2, "División: ", n1/n2  )

pregunta=False
print(pregunta)

n1=5
n2=6
print(n1>=n2)

n1=5.9
n2=6.0
print(n1==n2)

var1=True
var2=False
print(var1 and var2)

i=int(input('ingrese'))
print(i)