# -*- coding: utf-8 -*-
"""Untitled2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zMwkbTB0nSxFK3soLWouAoYfZ8yRwzM
"""

n1=int(input('Ingrese el primer numero: '))
n2=int(input('Ingrese el segundo numero: '))
print('Suma: ',n1+n2, 'Resta: ',n1-n2, 'Division: ', n1/n2, 'Multiplicacion: ',n1*n2)

nombre=input('Ingrese su nombre: ')
if len(nombre) >= 5:
  print('Tienes', len(nombre),'letras en tu nombre')
else:
  print('No tienes mas de 5 letras en tu nombre')

f=input('Ingrese una frase: ')
print('Tu frase tiene', len(f),'letras')

nombre=input('Ingrese su nombre: ')
apellido=input('Ingrese su apellido: ')
print('Su nombre completo es: ',nombre,apellido)

n=[3,5,6,9,5,10]
s=0
for i in range (len(n)):
  s=s+n[i]
print(s)

print('True and False =',True and False)
print('False and False =',False and False)
print('False and True =',False and True)
print('True and True =',True and True)

print('True or False =',True or False)
print('False or False =',False or False)
print('False or True =',False or True)
print('True or True =',True or True)

n1=int(input('Ingrese el primer numero: '))
n2=int(input('Ingrese el segundo numero: '))
if n1>n2:
  print('El primer numero es mas grandre que el segundo')
else:
  print('El segundo numero es mas grandre que el primero')

nombre=input('Ingrese su nombre: ')
edad=int(input('Ingrese su edad: '))
print('La edad de',nombre, 'es',edad,'años')

n1=int(input('Ingrese el primer numero: '))
n2=int(input('Ingrese el segundo numero: '))
if n1==n2:
  print('Los 2 numeros son iguales')
else:
  print('Los 2 numeros no son iguales')